# d√©finir le parti
default: &default
    title: France Insoumise
    panneau-ok: "FI-ok.png"
    panneau-no: "FI-no.png"
    sass: _settings_FI

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
